### ISSUE TITLE
make it online

### ISSUE THREAD

**Issue by tomasmcm** [g-mu/8x8-Animator#1]
If this project is a webpage why not make it online? You can do it here in github. Just create a new branch called 'gh-pages' and copy the files there. Then you would be able to access the website at https://g-mu.github.io/8x8-Animator

**Comment by g-mu** [comment]
Yup, I can do that too. Just thought the source was nice to put out there for other projects. I tend to like to run things locally when I diy.
Gordon.

On Sun, Nov 22, 2015 at 2:23 AM -0800, "Tomás Correia Marques" notifications@github.com wrote:

If this project is a webpage why not make it online? You can do it here in github. Just create a new branch called 'gh-pages' and copy the files there. Then you would be able to access the website at https://g-mu.github.io/8x8-Animator

---

Reply to this email directly or view it on GitHub:
https://github.com/g-mu/8x8-Animator/issues/1

**Comment by g-mu** [comment]
All done and online. Hope it's useful for someone else too.
Gordon.

Date: Sun, 22 Nov 2015 02:22:53 -0800

**Comment by tomasmcm** [comment]
Brilliant! You see I suggested this not because I thought you did wrong when sharing the source, but as something else you could do.
This way I can test your project directly on github without having to download and extract files...
Keep up the good work!
